(function(){
const bin=document.getElementById('bin'),q=document.getElementById('q'),count=document.getElementById('count'),filtersEl=document.getElementById('filters'),stage=document.getElementById('stage'),closeBtn=document.getElementById('close'),albumEl=document.getElementById('album'),rig=document.getElementById('rig'),faceFront=document.getElementById('faceFront'),faceBack=document.getElementById('faceBack'),dossier=document.getElementById('dossier'),viewBtns=document.getElementById('viewBtns'),flipBtn=document.getElementById('flip'),nearBtn=document.getElementById('near'),farBtn=document.getElementById('far'),needleRow=document.getElementById('needleRow'),platter=document.getElementById('platter'),arm=document.getElementById('arm');
const SEEDED=window.CATALOG||[],CRATE=window.PHOTO_CRATE||[],LIST=window.LIST_CATALOG||[],PHOTO=CRATE.concat(SEEDED);
window.CATALOG=PHOTO.concat(LIST);
let decade='all',format='all',havePhoto='photo',current=null,scale=1,pinching=false;
const SERVICES=[{id:'spotify',label:'Spotify',url:q=>'https://open.spotify.com/search/'+q},{id:'apple',label:'Apple Music',url:q=>'https://music.apple.com/us/search?term='+q},{id:'youtubemusic',label:'YouTube Music',url:q=>'https://music.youtube.com/search?q='+q},{id:'amazon',label:'Amazon Music',url:q=>'https://music.amazon.com/search/'+q},{id:'tidal',label:'Tidal',url:q=>'https://listen.tidal.com/search?q='+q}];
let preferred=localStorage.getItem('lr-service')||'spotify';
function haystack(a){return [a.title,a.artist,a.label,a.catalog,a.year,a.format,a.raw,a.notes,...(a.genre||[])].filter(Boolean).join(' ').toLowerCase()}
function matches(a,query){if(decade!=='all'){const y=Number(a.year),d0=Number(decade.slice(0,4));if(!(y>=d0&&y<=d0+9))return false}if(format!=='all'&&String(a.speed)!==format)return false;if(havePhoto==='photo'&&!a.images?.front)return false;if(havePhoto==='list'&&a.images?.front)return false;if(!query)return true;return query.split(/\s+/).every(t=>haystack(a).includes(t))}
function sorted(list){return list.slice().sort((x,y)=>(Number(x.year||0)-Number(y.year||0))||String(x.artist||'').localeCompare(String(y.artist||'')))}
function renderChips(){filtersEl.innerHTML='';[{values:['all','1940s','1950s','1960s','1970s','1980s'],get:()=>decade,set:v=>decade=v,prefix:'Decade'},{values:['all','78','45','33'],get:()=>format,set:v=>format=v,prefix:'Speed'},{values:['photo','list','all'],get:()=>havePhoto,set:v=>havePhoto=v,prefix:'Crate'}].forEach(g=>g.values.forEach(v=>{const b=document.createElement('button');b.className='chip'+(g.get()===v?' on':'');b.textContent=v==='all'?g.prefix+': all':v;b.onclick=()=>{g.set(v);draw()};filtersEl.appendChild(b)}))}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]))}
function draw(){renderChips();const query=q.value.trim().toLowerCase();const shown=sorted(window.CATALOG.filter(a=>matches(a,query)));count.textContent=shown.length+' in the crate';bin.innerHTML='';shown.slice(0,240).forEach(a=>{const btn=document.createElement('button');btn.className='sleeve';const art=a.images?.front?`<img src="${a.images.front}" alt="" loading="lazy">`:`<div class="blank-sleeve"><span>${escapeHtml((a.title||'?').slice(0,48))}</span></div>`;btn.innerHTML=`<div class="sleeve-art">${art}</div><div class="sleeve-meta"><p class="artist">${escapeHtml(a.artist||'Written list')}</p><p class="title">${escapeHtml(a.title||'')}</p></div>`;btn.onclick=()=>openAlbum(a);bin.appendChild(btn)})}
function imgs(a){return a.images||{}}
function setFace(el,src){el.style.backgroundImage=src?`url("${src}")`:'none'}
function applyView(view){if(view==='back'||view==='inner'){albumEl.classList.add('flipped');setFace(faceBack,imgs(current)[view]||imgs(current).back||imgs(current).front)}else{albumEl.classList.remove('flipped');setFace(faceFront,imgs(current).front)}}
function queryFor(a){return encodeURIComponent([a.artist,a.title].filter(Boolean).join(' '))}
function renderServices(){const el=document.getElementById('servicePicks');if(!el)return;el.innerHTML='';SERVICES.forEach(s=>{const b=document.createElement('button');b.className='chip'+(preferred===s.id?' on':'');b.textContent=s.label;b.onclick=()=>{preferred=s.id;localStorage.setItem('lr-service',preferred);renderServices();if(current)paintNeedle(current)};el.appendChild(b)})}
function paintNeedle(a){const svc=SERVICES.find(s=>s.id===preferred)||SERVICES[0];needleRow.innerHTML=`<a class="drop" href="${svc.url(queryFor(a))}" target="_blank" rel="noopener">Drop the needle · ${svc.label}</a>`}
function applyScale(){rig.style.transform='scale('+scale+')'}
function openAlbum(a){current=a;stage.hidden=false;document.body.style.overflow='hidden';scale=1;applyScale();setFace(faceFront,imgs(a).front);setFace(faceBack,imgs(a).back||imgs(a).front);albumEl.classList.remove('flipped');paintNeedle(a);viewBtns.innerHTML='';[['front','Front'],['back','Back'],['inner','Inside']].forEach(([id,label])=>{if(id!=='front'&&!imgs(a)[id])return;const b=document.createElement('button');b.textContent=label;b.onclick=()=>applyView(id);viewBtns.appendChild(b)});dossier.innerHTML=`<h2>${escapeHtml(a.title||'')}</h2><p class="byline">${escapeHtml(a.artist||'')}</p><dl class="meta-grid"><dt>Issued</dt><dd>${a.year||'—'}</dd><dt>Label</dt><dd>${escapeHtml([a.label,a.catalog].filter(Boolean).join(' · ')||'—')}</dd></dl>`;stage.scrollTop=0}
function close(){stage.hidden=true;document.body.style.overflow='';current=null;scale=1;applyScale()}
q.addEventListener('input',draw);closeBtn.onclick=close;flipBtn.onclick=()=>{if(!current)return;applyView(albumEl.classList.contains('flipped')?'front':'back')};nearBtn.onclick=()=>{scale=Math.min(3,scale+0.35);applyScale()};farBtn.onclick=()=>{scale=Math.max(1,scale-0.35);applyScale()};albumEl.onclick=()=>{if(!pinching)flipBtn.click()};
let startX=0,pinchStart=0,pinchBase=1;
function fingerDist(t){return Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY)}
albumEl.addEventListener('touchstart',e=>{if(e.touches.length===2){pinching=true;pinchStart=fingerDist(e.touches);pinchBase=scale}else startX=e.changedTouches[0].clientX},{passive:true});
albumEl.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchStart){e.preventDefault();scale=Math.min(3,Math.max(1,pinchBase*(fingerDist(e.touches)/pinchStart)));applyScale()}},{passive:false});
albumEl.addEventListener('touchend',e=>{if(pinching){if(e.touches.length===0)pinching=false;return}if(Math.abs(e.changedTouches[0].clientX-startX)>40)flipBtn.click()},{passive:true});
renderServices();draw();
})();
